### ISSUE TITLE
Theta X support?

### ISSUE THREAD

**Issue by biviel** [ricohapi/theta-wireless-live-streaming-plugin#3]
The plugin available in Ricoh Store already supports Theta X. Would be really useful to have a working sample code that also supports Theta X. Would you be king and make this compatible with Theta X, or put some guidelines together for developers to see how a live preview should be handled in plugins? 

Thanks!

**Comment by safavakili** [comment]
I also appreciate if this repository gets updated with Theta X support changes.

Cheers

**Comment by codetricity** [comment]
Have you tried this branch that was just released?  https://github.com/ricohapi/theta-wireless-live-streaming-plugin/tree/release/v1.2.1

**Comment by DaisukeHohjoh** [comment]
Now we merged release/v1.2.1 to master branch. It supports RICOH THETA X.

**Comment by biviel** [comment]
Hi! I'm testing this change and support for Theta X today. thanks!
