### ISSUE TITLE
Releases don't include builds

### ISSUE THREAD

**Issue by Utopiah** [ricohapi/theta-wireless-live-streaming-plugin#5]
Hi, I noticed that there is no apk available. Unfortunately the official store requires an app to download and install the apk. Even if I wanted to install an app for that, which to be honest I do not, I still could not as my operating system, Ubuntu, is not supported. Consequently could you please also include builds as `.apk` to install via `adb` in releases?

**Comment by DaisukeHohjoh** [comment]
Hi,

RICOH released v1.2.3 yesterday, and attached build apk. Please check it.
https://github.com/ricohapi/theta-wireless-live-streaming-plugin/releases/tag/v1.2.3

I am very sorry for our later response to your request.
